name: Build LaTeX document
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master
      - name: run all python scripts 
        run: |
          echo $PATH
          . .venv/bin/activate
          python get_papers.py -id "0000-0003-1997-3649"
          python papers_to_tex.py -i papers.json -o main.tex -a "Patrick Armstrong"
        shell: sh
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: complete_main.tex
      - name: Configure Git and push changes
        run: |
          git config --global user.email "patrick.armstrong@anu.edu.au"
          git config --global user.name "Patrick Armstrong"
          git add main.pdf
          git commit -m "Add complete_main.pdf"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
