name: Build LaTeX document
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@master
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
      - name: Configure Git and push changes
        run: |
          git config --global user.email "patrick.armstrong@anu.edu.au"
          git config --global user.name "Patrick Armstrong"
          git add main.pdf
          git commit -m "Add main.pdf"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
