name: Build LaTeX document
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
